In [5]:
import pandas as pd
import csv

In [6]:
# Load data from git.csv
df = pd.read_csv('git.csv', sep='|', quoting=csv.QUOTE_MINIMAL, escapechar='\\')
df.head()

,Unnamed: 0,project,file,date_start,date_end,library,about
0,0,alice,server.py,2020-06-02 17:02:29,2020-06-02 20:24:54,asyncio,SImple Alice skill python server
1,1,alice,server.py,2020-06-02 17:02:29,2020-06-02 20:24:54,ssl,SImple Alice skill python server
2,2,alice,server.py,2020-06-02 17:02:29,2020-06-02 20:24:54,firebase_admin,SImple Alice skill python server
3,3,alice,server.py,2020-06-02 17:02:29,2020-06-02 20:24:54,aiohttp,SImple Alice skill python server
4,4,alice,server.py,2020-06-02 17:02:29,2020-06-02 20:24:54,firebase_admin,SImple Alice skill python server

In [7]:
# drop all columns except of library
df = pd.DataFrame(df['library'])
df.head()

          library
0         asyncio
1             ssl
2  firebase_admin
3         aiohttp
4  firebase_admin

In [8]:
# Get the unique values of the library column
unique_values = df['library'].unique()
len(unique_values)

645

In [9]:
# Save the unique values to a file: unique_libraries.txt
with open('unique_libraries.txt', 'w') as f:
    for item in unique_values:
        f.write("%s\n" % item)

In [10]:
# Convert each item to text
unique_values = [str(x) for x in unique_values]

#### GPT: Get list of categories

In [11]:
# Ask user the OpenAI token: https://platform.openai.com/account/api-keys
openai_key = input("Enter OpenAI api-key: ")

In [12]:
from openai import OpenAI

def llm_request(model, api_key, messages):
    client = OpenAI(api_key=api_key)

    response = client.chat.completions.create(
        model=model,
        messages=messages
    )
    return response.choices[0].message.content

In [13]:
import re
import json

def extract_json_from_llm_answer(llm_answer):
    # Find the JSON structure using regex
    json_match = re.search(r'```json\n([\s\S]*?)\n```', llm_answer)
    
    if json_match:
        json_str = json_match.group(1)
        try:
            # Parse the extracted JSON string
            json_data = json.loads(json_str)
            return json_data
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")
            return None
    else:
        print("No JSON structure found in the LLM answer.")
        return None

In [14]:
system_content = "You are a Python library expert."
cat_count = 24
user_content = f"""There is a list of libraries. You need to determine about {cat_count} categories, that these libraries belong to in general.
"""
# Concatenate a list of libraries as a string with spaces
user_content = " ".join(unique_values)
user_content += f"""
Left one category for "other" category. Provide your list of categories in JSON format. For example:
["Natural language processing", "Data Visualization", "Computer vision", "Speech recognition", "Speech synthesis", "CUDA development", "Distributed Computing", "Others"]
and so on. {cat_count} categories in total. Don't represent the libraries. I need only a list of catefgores."""
messages=[
        {"role": "system", "content": system_content},
        {"role": "user", "content": user_content}
    ]

In [15]:
###  Pricing:
# [0.5:0.25] gpt-3.5-turbo-0125
# [1:2] gpt-3.5-turbo-1106
# [1.5:2] gpt-3.5-turbo-0613
# [5:2.5] gpt-4o
model = "gpt-4o"

In [16]:
engine = "openai"
answer = llm_request(model, openai_key, messages)
answer

'```json\n[\n    "Natural Language Processing",\n    "Data Visualization",\n    "Computer Vision",\n    "Speech Recognition",\n    "Speech Synthesis",\n    "CUDA Development",\n    "Distributed Computing",\n    "Web Development",\n    "API Development",\n    "Database Management",\n    "Analytics",\n    "Machine Learning",\n    "Deep Learning",\n    "Reinforcement Learning",\n    "Data Processing",\n    "Cryptography",\n    "Networking",\n    "Command Line Utilities",\n    "Web Scraping",\n    "Testing",\n    "Virtualization and Containers",\n    "Optimization",\n    "Automation",\n    "Others"\n]\n```'

In [17]:
categories = extract_json_from_llm_answer(answer)
# # Get list of keys
# categories = list(extracted_json.keys())
print(len(categories))
categories

24

['Natural Language Processing',
 'Data Visualization',
 'Computer Vision',
 'Speech Recognition',
 'Speech Synthesis',
 'CUDA Development',
 'Distributed Computing',
 'Web Development',
 'API Development',
 'Database Management',
 'Analytics',
 'Machine Learning',
 'Deep Learning',
 'Reinforcement Learning',
 'Data Processing',
 'Cryptography',
 'Networking',
 'Command Line Utilities',
 'Web Scraping',
 'Testing',
 'Virtualization and Containers',
 'Optimization',
 'Automation',
 'Others']

#### GPT: determine the category of each library

In [20]:
###  Pricing:
# [0.5:0.25] gpt-3.5-turbo-0125
# [1:2] gpt-3.5-turbo-1106
# [1.5:2] gpt-3.5-turbo-0613
# [5:2.5] gpt-4o

model = "gpt-3.5-turbo-0125"
print("Categories count:", len(unique_values))
system_content = "You are a Python library expert."
current_category = 0
library_dict = {}
for library in unique_values:
    user_content = f"""Categorize the Python library "{library}" into exactly one of these categories:
{categories}

Respond with ONLY the category name, nothing else. If unsure, choose the closest match."""
    messages=[
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content}
        ]
    answer = llm_request(model, openai_key, messages)
    print(f"[{current_category} / {len(unique_values)}] Library: {library}, Category: {answer}")
    library_dict[library] = answer.replace("'", "")
    current_category += 1
print(f"library_dict length: {len(library_dict)}")

Categories count: 645
[0 / 645] Library: asyncio, Category: Distributed Computing
[1 / 645] Library: ssl, Category: Cryptography
[2 / 645] Library: firebase_admin, Category: Database Management
[3 / 645] Library: aiohttp, Category: Web Development
[4 / 645] Library: json, Category: Data Processing
[5 / 645] Library: logging, Category: Others
[6 / 645] Library: pymysql, Category: Database Management
[7 / 645] Library: pandas, Category: Data Processing
[8 / 645] Library: time, Category: Data Processing
[9 / 645] Library: random, Category: Others
[10 / 645] Library: string, Category: Data Processing
[11 / 645] Library: difflib, Category: Others
[12 / 645] Library: __future__, Category: Others
[13 / 645] Library: flask, Category: Web Development
[14 / 645] Library: tongue_twister, Category: Others
[15 / 645] Library: requests, Category: Web Development
[16 / 645] Library: urllib, Category: Web Development
[17 / 645] Library: datetime, Category: Data Processing
[18 / 645] Library: os, Category: Others
[19 / 645] Library: audio_sql_proc, Category: Audio SQL Processing falls under the category of 'Data Processing'.
[20 / 645] Library: uuid, Category: Others
[21 / 645] Library: bip_utils, Category: Cryptography
[22 / 645] Library: numpy, Category: Others
[23 / 645] Library: pycuda, Category: CUDA Development
[24 / 645] Library: inspect, Category: Others
[25 / 645] Library: hashlib, Category: Cryptography
[26 / 645] Library: filecmp, Category: Data Processing
[27 / 645] Library: typing, Category: Others
[28 / 645] Library: typos, Category: Natural Language Processing
[29 / 645] Library: Crypto, Category: Cryptography
[30 / 645] Library: abc, Category: Others
[31 / 645] Library: ed25519, Category: Cryptography
[32 / 645] Library: base58, Category: Cryptography
[33 / 645] Library: ecdsa, Category: Cryptography
[34 / 645] Library: pycryptodome, Category: Cryptography
[35 / 645] Library: binascii, Category: Cryptography
[36 / 645] Library: hmac, Category: Cryptography
[37 / 645] Library: struct, Category: Data Processing
[38 / 645] Library: web3, Category: Blockchain Development
[39 / 645] Library: mnemonic, Category: Cryptography
[40 / 645] Library: snakeviz, Category: Data Visualization
[41 / 645] Library: collections, Category: Data Processing
[42 / 645] Library: nan, Category: Others
[43 / 645] Library: torch, Category: Deep Learning
[44 / 645] Library: math, Category: Others
[45 / 645] Library: torchvision, Category: Computer Vision
[46 / 645] Library: PIL, Category: Computer Vision
[47 / 645] Library: glob, Category: Data Processing
[48 / 645] Library: cv2, Category: Computer Vision
[49 / 645] Library: argparse, Category: Command Line Utilities
[50 / 645] Library: model, Category: Machine Learning
[51 / 645] Library: shutil, Category: Data Processing
[52 / 645] Library: threading, Category: Distributed Computing
[53 / 645] Library: tqdm, Category: Others
[54 / 645] Library: dataset, Category: Database Management
[55 / 645] Library: inference_utils, Category: Machine Learning
[56 / 645] Library: kornia, Category: Computer Vision
[57 / 645] Library: tensorboard, Category: Deep Learning
[58 / 645] Library: data_path, Category: Data Processing
[59 / 645] Library: plotly, Category: Data Visualization
[60 / 645] Library: seaborn, Category: Data Visualization
[61 / 645] Library: colorsys, Category: Data Processing
[62 / 645] Library: matplotlib, Category: Data Visualization
[63 / 645] Library: deeppavlov, Category: Natural Language Processing
[64 / 645] Library: models, Category: Machine Learning
[65 / 645] Library: util, Category: Command Line Utilities
[66 / 645] Library: resource, Category: Others
[67 / 645] Library: re, Category: Others
[68 / 645] Library: sys, Category: Others
[69 / 645] Library: user_defined, Category: Others
[70 / 645] Library: fastapi, Category: API Development
[71 / 645] Library: scipy, Category: Machine Learning
[72 / 645] Library: ipython, Category: Others
[73 / 645] Library: sympy, Category: Others
[74 / 645] Library: nose, Category: Testing
[75 / 645] Library: pyTelegramBotAPI, Category: API Development
[76 / 645] Library: uvicorn, Category: Web Development
[77 / 645] Library: subprocess, Category: Automation
[78 / 645] Library: ast, Category: Data Processing
[79 / 645] Library: telebot, Category: API Development
[80 / 645] Library: starlette, Category: Web Development
[81 / 645] Library: pymssql, Category: Database Management
[82 / 645] Library: wave, Category: Data Processing
[83 / 645] Library: contextlib, Category: Others
[84 / 645] Library: websockets, Category: Networking
[85 / 645] Library: socket, Category: Networking
[86 / 645] Library: httpx, Category: Web Development
[87 / 645] Library: ruts, Category: Data Processing
[88 / 645] Library: PyMySQL, Category: Database Management
[89 / 645] Library: pendulum, Category: Data Processing
[90 / 645] Library: urllib3, Category: Networking
[91 / 645] Library: cryptography, Category: Cryptography
[92 / 645] Library: init_server, Category: Web Development
[93 / 645] Library: init_queue, Category: Data Processing
[94 / 645] Library: twocaptcha, Category: Automation
[95 / 645] Library: gym, Category: Reinforcement Learning
[96 / 645] Library: stable_baselines3, Category: Reinforcement Learning
[97 / 645] Library: pyvirtualdisplay, Category: Virtualization and Containers
[98 / 645] Library: huggingface_sb3, Category: Natural Language Processing
[99 / 645] Library: huggingface_hub, Category: Natural Language Processing
[100 / 645] Library: itertools, Category: Data Processing
[101 / 645] Library: pygame, Category: Computer Vision
[102 / 645] Library: huggingface-sb3, Category: Natural Language Processing
[103 / 645] Library: stable-baselines3, Category: Reinforcement Learning
[104 / 645] Library: box2d-py, Category: Physics Simulation
[105 / 645] Library: tensorflow-gpu, Category: Deep Learning
[106 / 645] Library: pyglet, Category: Others
[107 / 645] Library: IPython, Category: Others
[108 / 645] Library: colabgymrender, Category: Reinforcement Learning
[109 / 645] Library: _libgcc_mutex, Category: Others
[110 / 645] Library: _openmp_mutex, Category: Optimization
[111 / 645] Library: _tflow_select, Category: Deep Learning
[112 / 645] Library: abseil-cpp, Category: Others
[113 / 645] Library: absl-py, Category: Others
[114 / 645] Library: aiosignal, Category: Distributed Computing
[115 / 645] Library: astor, Category: Data Processing
[116 / 645] Library: astunparse, Category: Data Processing
[117 / 645] Library: async-timeout, Category: Networking
[118 / 645] Library: attrs, Category: Others
[119 / 645] Library: blas, Category: Optimization
[120 / 645] Library: blinker, Category: Others
[121 / 645] Library: brotlipy, Category: Cryptography
[122 / 645] Library: c-ares, Category: Networking
[123 / 645] Library: ca-certificates, Category: Cryptography
[124 / 645] Library: cachetools, Category: Others
[125 / 645] Library: certifi, Category: Cryptography
[126 / 645] Library: cffi, Category: Cryptography
[127 / 645] Library: charset-normalizer, Category: Data Processing
[128 / 645] Library: click, Category: Command Line Utilities
[129 / 645] Library: cloudpickle, Category: Distributed Computing
[130 / 645] Library: dataclasses, Category: Data Processing
[131 / 645] Library: flatbuffers, Category: Data Processing
[132 / 645] Library: frozenlist, Category: Others
[133 / 645] Library: gast, Category: Deep Learning
[134 / 645] Library: giflib, Category: Data Visualization
[135 / 645] Library: google-auth, Category: API Development
[136 / 645] Library: google-auth-oauthlib, Category: API Development
[137 / 645] Library: google-pasta, Category: Deep Learning
[138 / 645] Library: grpcio, Category: Networking
[139 / 645] Library: gym-notices, Category: Reinforcement Learning
[140 / 645] Library: h5py, Category: Data processing
[141 / 645] Library: hdf5, Category: Data Processing
[142 / 645] Library: icu, Category: Natural Language Processing
[143 / 645] Library: idna, Category: Cryptography
[144 / 645] Library: importlib-metadata, Category: Others
[145 / 645] Library: intel-openmp, Category: Optimization
[146 / 645] Library: jpeg, Category: Computer Vision
[147 / 645] Library: keras-preprocessing, Category: Deep Learning
[148 / 645] Library: krb5, Category: Cryptography
[149 / 645] Library: ld_impl_linux-64, Category: Others
[150 / 645] Library: libcurl, Category: Networking
[151 / 645] Library: libedit, Category: Command Line Utilities
[152 / 645] Library: libev, Category: Distributed Computing
[153 / 645] Library: libffi, Category: Others
[154 / 645] Library: libgcc-ng, Category: Others
[155 / 645] Library: libgfortran-ng, Category: Others
[156 / 645] Library: libgfortran4, Category: Others
[157 / 645] Library: libgomp, Category: Optimization
[158 / 645] Library: libnghttp2, Category: Networking
[159 / 645] Library: libpng, Category: Data Processing
[160 / 645] Library: libprotobuf, Category: Data Processing
[161 / 645] Library: libssh2, Category: Networking
[162 / 645] Library: libstdcxx-ng, Category: Others
[163 / 645] Library: markdown, Category: Web Development
[164 / 645] Library: mkl, Category: Optimization
[165 / 645] Library: mkl-service, Category: Optimization
[166 / 645] Library: mkl_fft, Category: Optimization
[167 / 645] Library: mkl_random, Category: Optimization
[168 / 645] Library: multidict, Category: Data Processing
[169 / 645] Library: ncurses, Category: Command Line Utilities
[170 / 645] Library: numpy-base, Category: Data Processing
[171 / 645] Library: oauthlib, Category: API Development
[172 / 645] Library: openssl, Category: Cryptography
[173 / 645] Library: opt_einsum, Category: Optimization
[174 / 645] Library: pip, Category: Others
[175 / 645] Library: protobuf, Category: Others
[176 / 645] Library: pyasn1, Category: Cryptography
[177 / 645] Library: pyasn1-modules, Category: Cryptography
[178 / 645] Library: pycparser, Category: Parsing and AST generation
[179 / 645] Library: pyjwt, Category: Cryptography
[180 / 645] Library: pyopenssl, Category: Cryptography
[181 / 645] Library: pysocks, Category: Networking
[182 / 645] Library: python, Category: Automation
[183 / 645] Library: python-flatbuffers, Category: Others
[184 / 645] Library: readline, Category: Command Line Utilities
[185 / 645] Library: requests-oauthlib, Category: API Development
[186 / 645] Library: rsa, Category: Cryptography
[187 / 645] Library: setuptools, Category: Web Development
[188 / 645] Library: six, Category: Others
[189 / 645] Library: snappy, Category: Compression
[190 / 645] Library: sqlite, Category: Database Management
[191 / 645] Library: tensorboard-data-server, Category: Data Visualization
[192 / 645] Library: tensorboard-plugin-wit, Category: Deep Learning
[193 / 645] Library: tensorflow, Category: Deep Learning
[194 / 645] Library: tensorflow-base, Category: Deep Learning
[195 / 645] Library: tensorflow-estimator, Category: Deep Learning
[196 / 645] Library: termcolor, Category: Command Line Utilities
[197 / 645] Library: tk, Category: User Interface (GUI) Development
[198 / 645] Library: typing-extensions, Category: Others
[199 / 645] Library: typing_extensions, Category: Others
[200 / 645] Library: werkzeug, Category: Web Development
[201 / 645] Library: wheel, Category: Others
[202 / 645] Library: wrapt, Category: Automation
[203 / 645] Library: xz, Category: Others
[204 / 645] Library: yarl, Category: Web Development
[205 / 645] Library: zipp, Category: Data Processing
[206 / 645] Library: zlib, Category: Data Processing
[207 / 645] Library: catboost, Category: Machine Learning
[208 / 645] Library: sklearn, Category: Machine Learning
[209 / 645] Library: scikit-learn, Category: Machine Learning
[210 / 645] Library: io, Category: Data Processing
[211 / 645] Library: opencv-contrib-python, Category: Computer Vision
[212 / 645] Library: openai, Category: Natural Language Processing
[213 / 645] Library: zipfile, Category: Data Processing
[214 / 645] Library: transformers, Category: Natural Language Processing
[215 / 645] Library: sentencepiece, Category: Natural Language Processing
[216 / 645] Library: google, Category: API Development
[217 / 645] Library: google-cloud-storage, Category: Others
[218 / 645] Library: shlex, Category: Command Line Utilities
[219 / 645] Library: streamlink, Category: Web Scraping
[220 / 645] Library: ffmpeg, Category: Others
[221 / 645] Library: whisper, Category: Data Processing
[222 / 645] Library: openai-whisper, Category: Natural Language Processing
[223 / 645] Library: anthropic, Category: Machine Learning
[224 / 645] Library: cleaner_bot_script, Category: Automation
[225 / 645] Library: python3, Category: Others
[226 / 645] Library: stat, Category: Statistics
[227 / 645] Library: icetk, Category: Deep Learning
[228 / 645] Library: SwissArmyTransformer, Category: Machine Learning
[229 / 645] Library: coglm_strategy, Category: Machine Learning
[230 / 645] Library: multiprocessing, Category: Distributed Computing
[231 / 645] Library: tkinter, Category: User Interface Development
[232 / 645] Library: deepspeed, Category: Deep Learning
[233 / 645] Library: gifmaker, Category: Data Visualization
[234 / 645] Library: configparser, Category: Data Processing
[235 / 645] Library: pydantic, Category: Validation
[236 / 645] Library: dalle2, Category: Deep Learning
[237 / 645] Library: image_converter, Category: Computer Vision
[238 / 645] Library: dalee_generator, Category: Data Processing
[239 / 645] Library: base64, Category: Cryptography
[240 / 645] Library: pathlib, Category: Data Processing
[241 / 645] Library: ale-py, Category: Machine Learning
[242 / 645] Library: stable_baselines, Category: Reinforcement Learning
[243 / 645] Library: pickle, Category: Data Processing
[244 / 645] Library: tokenizer_for_jupyter, Category: Natural Language Processing
[245 / 645] Library: ipywidgets, Category: Web Development
[246 / 645] Library: SpeechRecognition, Category: Speech Recognition
[247 / 645] Library: pyttsx3, Category: Speech Synthesis
[248 / 645] Library: speech_recognition, Category: Speech Recognition
[249 / 645] Library: redis, Category: Database Management
[250 / 645] Library: boto3, Category: API Development
[251 / 645] Library: botocore, Category: Networking
[252 / 645] Library: chardet, Category: Data Processing
[253 / 645] Library: cycler, Category: Data Visualization
[254 / 645] Library: docker, Category: Virtualization and Containers
[255 / 645] Library: docutils, Category: Others
[256 / 645] Library: future, Category: Others
[257 / 645] Library: iterable-queue, Category: Data Processing
[258 / 645] Library: jmespath, Category: Data Processing
[259 / 645] Library: kiwisolver, Category: Optimization
[260 / 645] Library: ntlm-auth, Category: Networking
[261 / 645] Library: Pillow, Category: Image Processing
[262 / 645] Library: pyparsing, Category: Data Processing
[263 / 645] Library: python-dateutil, Category: Data Processing
[264 / 645] Library: PyYAML, Category: Data Processing
[265 / 645] Library: regex, Category: Data Processing
[266 / 645] Library: requests-ntlm, Category: Networking
[267 / 645] Library: s3transfer, Category: Distributed Computing
[268 / 645] Library: smmap2, Category: Others
[269 / 645] Library: wincertstore, Category: Cryptography
[270 / 645] Library: bz2, Category: Data Processing
[271 / 645] Library: shared, Category: Data Processing
[272 / 645] Library: master, Category: Web Development
[273 / 645] Library: feeder, Category: Data Processing
[274 / 645] Library: transformers19, Category: Natural Language Processing
[275 / 645] Library: score, Category: Machine Learning
[276 / 645] Library: copy, Category: Others
[277 / 645] Library: tempfile, Category: Data Processing
[278 / 645] Library: fnmatch, Category: Others
[279 / 645] Library: functools, Category: Others
[280 / 645] Library: flask_cors, Category: Web Development
[281 / 645] Library: RPi, Category: Others
[282 / 645] Library: picamera, Category: Computer Vision
[283 / 645] Library: psycopg2, Category: Database Management
[284 / 645] Library: pyaudio, Category: Audio Processing
[285 / 645] Library: PyAudio, Category: Audio Processing
[286 / 645] Library: dask, Category: Distributed Computing
[287 / 645] Library: diffusers, Category: Data Processing
[288 / 645] Library: gpiozero, Category: Others
[289 / 645] Library: getopt, Category: Command Line Utilities
[290 / 645] Library: ina219, Category: Others
[291 / 645] Library: keras, Category: Deep Learning
[292 / 645] Library: geopy, Category: Others
[293 / 645] Library: pytz, Category: Others
[294 / 645] Library: github, Category: API Development
[295 / 645] Library: PyGithub, Category: API Development
[296 / 645] Library: google-cloud-speech, Category: Speech Recognition
[297 / 645] Library: Flask, Category: Web Development
[298 / 645] Library: ftfy, Category: Data Processing
[299 / 645] Library: encoder, Category: Cryptography
[300 / 645] Library: tarfile, Category: Data Processing
[301 / 645] Library: newspaper, Category: Web Scraping
[302 / 645] Library: extract_text, Category: Web Scraping
[303 / 645] Library: tpu_survival, Category: Machine Learning
[304 / 645] Library: experiments, Category: Machine Learning
[305 / 645] Library: signal, Category: Others
[306 / 645] Library: googleapiclient, Category: API Development
[307 / 645] Library: oauth2client, Category: API Development
[308 / 645] Library: inputs, Category: Command Line Utilities
[309 / 645] Library: model_fns, Category: Deep Learning
[310 / 645] Library: predict_fns, Category: Machine Learning
[311 / 645] Library: lex, Category: Others
[312 / 645] Library: language_translate, Category: Natural Language Processing
[313 / 645] Library: sql_lib, Category: Database Management
[314 / 645] Library: optimizers, Category: Optimization
[315 / 645] Library: metric_fns, Category: Machine Learning
[316 / 645] Library: flask-sslify, Category: Web Development
[317 / 645] Library: beautifulsoup4, Category: Web Scraping
[318 / 645] Library: bs4, Category: Web Scraping
[319 / 645] Library: adafruit_servokit, Category: Automation
[320 / 645] Library: GPUtil, Category: Others
[321 / 645] Library: gym_lex, Category: Reinforcement Learning
[322 / 645] Library: hodler, Category: Cryptography
[323 / 645] Library: pytelegrambotapi, Category: API Development
[324 / 645] Library: lxml, Category: Data Processing
[325 / 645] Library: tiktoken, Category: Web Scraping
[326 / 645] Library: csv, Category: Data Processing
[327 / 645] Library: panthera, Category: Machine Learning
[328 / 645] Library: aiofiles, Category: 'Async I/O'
[329 / 645] Library: langchain, Category: Natural Language Processing
[330 / 645] Library: langchain_experimental, Category: Machine Learning
[331 / 645] Library: langchain_community, Category: Others
[332 / 645] Library: langchain_openai, Category: Natural Language Processing
[333 / 645] Library: zeep, Category: API Development
[334 / 645] Library: docarray, Category: Data Processing
[335 / 645] Library: streamlit, Category: Data Visualization
[336 / 645] Library: langchain-experimental, Category: Natural Language Processing
[337 / 645] Library: config_manager, Category: 'Others'
[338 / 645] Library: chat_history_service, Category: Database Management
[339 / 645] Library: photo_description_service, Category: Computer Vision
[340 / 645] Library: onecproxy, Category: Networking
[341 / 645] Library: langchain_environment, Category: Others
[342 / 645] Library: onec_request, Category: API Development
[343 / 645] Library: httplib2, Category: Networking
[344 / 645] Library: Jetson, Category: Computer Vision
[345 / 645] Library: environment, Category: Web Development
[346 / 645] Library: debug, Category: Command Line Utilities
[347 / 645] Library: tensorboardX, Category: Deep Learning
[348 / 645] Library: cufflinks, Category: Data Visualization
[349 / 645] Library: learntools, Category: Others
[350 / 645] Library: kaggle_environments, Category: Reinforcement Learning
[351 / 645] Library: gc, Category: Others

In [22]:
list(library_dict.values())[-10:]

['Automation',
 'Machine Learning',
 'Data Processing',
 'API Development',
 'API Development',
 'Testing',
 'Data Processing',
 'Text Processing',
 'Web Scraping',
 'Data Processing']

In [23]:
print(f"library_dict.values set length: {len(set(library_dict.values()))}")
# Iterate in the ilbrary keys and replace value by 'Others' if it is not in the categories list
for key in library_dict.keys():
    if library_dict[key] not in categories:
        library_dict[key] = "Others"
print(f"library_dict.values set length: {len(set(library_dict.values()))}")

library_dict.values set length: 42
library_dict.values set length: 23

In [24]:
# Save json to cat.json
with open('cat.json', 'w') as f:
    json.dump(library_dict, f)